# Generated by Django 2.2.7 on 2020-02-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0002_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='Expertise',
        ),
    ]
