# Generated by Django 2.2.7 on 2020-02-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0003_auto_20200205_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='content',
            new_name='Profile',
        ),
    ]
