# Generated by Django 2.2.7 on 2020-02-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0005_auto_20200207_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Description',
            new_name='Background',
        ),
    ]
