# Generated by Django 2.2.7 on 2020-02-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0007_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('logo', 'LOGO'), ('tarpaulin', 'TARPAULIN LAYOUT'), ('advertisement', 'ADVERTISEMENT LAYOUT'), ('invitation', 'INVITATION LAYOUT'), ('souvenir', 'SOUVENIR')], default='logo', max_length=11),
        ),
    ]
