# Generated by Django 2.2.7 on 2020-02-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0012_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(choices=[('Malolos, Bungahan', 'Malolos, Bungahan'), ('Malolos, Longos', 'Malolos, Longos'), ('Malolos, Caliligawan', 'Malolos, Caliligawan'), ('Malolos, Tikay', 'Malolos, Tikay'), ('Malolos, Santol', 'Malolos, Santol')], default='Malolos, Bungahan', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Malolos, Bungahan', 'Malolos, Bungahan'), ('Malolos, Longos', 'Malolos, Longos'), ('Malolos, Caliligawan', 'Malolos, Caliligawan'), ('Malolos, Tikay', 'Malolos, Tikay'), ('Malolos, Santol', 'Malolos, Santol')], default='Malolos, Bungahan', max_length=30),
        ),
    ]
