# Generated by Django 2.2.7 on 2020-02-20 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home_Business', '0015_bidding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bidding',
            new_name='Bid',
        ),
    ]
