# Generated by Django 2.2.7 on 2020-02-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0017_auto_20200220_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
