# Generated by Django 2.2.7 on 2020-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0018_auto_20200222_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AddField(
            model_name='apply',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AddField(
            model_name='apply',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AddField(
            model_name='bid',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
