# Generated by Django 2.2.7 on 2020-02-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0019_auto_20200224_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='image1',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='image2',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='image3',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics'),
        ),
    ]
