# Generated by Django 2.2.7 on 2020-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0020_auto_20200224_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='post_pics'),
        ),
    ]
