# Generated by Django 2.2.7 on 2020-02-29 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home_Business', '0021_auto_20200224_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactNumber', models.IntegerField(max_length=11)),
                ('EmailAddress', models.CharField(max_length=30)),
                ('Message', models.TextField()),
                ('image', models.ImageField(default='plain.jpg', upload_to='post_pics')),
                ('location', models.CharField(choices=[('Malolos, Bungahan', 'Malolos, Bungahan'), ('Malolos, Longos', 'Malolos, Longos'), ('Malolos, Caliligawan', 'Malolos, Caliligawan'), ('Malolos, Tikay', 'Malolos, Tikay'), ('Malolos, Santol', 'Malolos, Santol')], default='Malolos, Bungahan', max_length=30)),
                ('dateposted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
