# Generated by Django 2.2.7 on 2020-02-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0022_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept',
            name='ContactNumber',
        ),
    ]
