# Generated by Django 2.2.7 on 2020-02-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0024_remove_accept_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept',
            name='Business_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
