# Generated by Django 2.2.7 on 2020-02-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0025_accept_business_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept',
            name='ContactNumber',
            field=models.CharField(default='', max_length=11),
        ),
    ]
