# Generated by Django 2.2.7 on 2020-02-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0026_accept_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept',
            name='EmailAddress',
        ),
    ]
