# Generated by Django 2.2.7 on 2020-03-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0031_auto_20200309_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-dateposted']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateposted']},
        ),
    ]
