# Generated by Django 2.2.7 on 2020-04-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0033_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-dateposted']},
        ),
    ]
