# Generated by Django 2.2.7 on 2020-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0038_auto_20200413_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='street',
            field=models.CharField(choices=[('Anilao', 'Anilao'), ('Atlag', 'Atlag'), ('Babatnin', 'Babatnin'), ('Bagna', 'Bagna'), ('Bagong Bayan', 'Bagong Bayan'), ('Balayong', 'Balayong'), ('Balite', 'Balite'), ('Bangkal', 'Bangkal'), ('Barihan', 'Barihan'), ('Bulihan', 'Bulihan'), ('Bungahan', 'Bungahan'), ('Caingin', 'Caingin'), ('Calero', 'Calero'), ('Caliligawan', 'Caliligawan'), ('Canalate', 'Canalate'), ('Caniogan', 'Caniogan'), ('Catmon', 'Catmon'), ('Cofradia', 'Cofradia'), ('Dakila', 'Dakila'), ('Guinhawa', 'Guinhawa'), ('Ligas', 'Ligas'), ('Liyang', 'Liyang'), ('longos', 'Longos'), ('Look 1st', 'Look 1st'), ('Look 2nd', 'Look 2nd'), ('Lugam', 'Lugam'), ('Mabolo', 'Mabolo'), ('Mambog', 'Mambog'), ('Masile', 'Masile'), ('Matimbo', 'Matimbo'), ('Mojon', 'Mojon'), ('Namayan', 'Namayan'), ('Niugan', 'Niugan'), ('Pamarawan', 'Pamarawan'), ('Panasahan', 'Panasahan'), ('Pinagbakahan', 'Pinagbakahan'), ('San Agustin', 'San Agustin'), ('San Gabriel', 'San Gabriel'), ('San Juan', 'San Juan'), ('San Pablo', 'San Pablo'), ('Santiago', 'Santiago'), ('Santisima Trinidad', 'Santisima Trinidad'), ('Santo Cristo', 'Santo Cristo'), ('Santor', 'Santor'), ('Santo Niño', 'Santo Niño'), ('Santo Rosario', 'Santo Rosario'), ('San Vicente', 'San Vicente'), ('Sumapang Bata', 'Sumapang Bata'), ('Sumapang Matanda', 'Sumapang Matanda'), ('taal', 'Taal'), ('tikay', 'Tikay')], default='Tikay', max_length=30, verbose_name='Enter your barangay'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='street',
            field=models.CharField(choices=[('Anilao', 'Anilao'), ('Atlag', 'Atlag'), ('Babatnin', 'Babatnin'), ('Bagna', 'Bagna'), ('Bagong Bayan', 'Bagong Bayan'), ('Balayong', 'Balayong'), ('Balite', 'Balite'), ('Bangkal', 'Bangkal'), ('Barihan', 'Barihan'), ('Bulihan', 'Bulihan'), ('Bungahan', 'Bungahan'), ('Caingin', 'Caingin'), ('Calero', 'Calero'), ('Caliligawan', 'Caliligawan'), ('Canalate', 'Canalate'), ('Caniogan', 'Caniogan'), ('Catmon', 'Catmon'), ('Cofradia', 'Cofradia'), ('Dakila', 'Dakila'), ('Guinhawa', 'Guinhawa'), ('Ligas', 'Ligas'), ('Liyang', 'Liyang'), ('longos', 'Longos'), ('Look 1st', 'Look 1st'), ('Look 2nd', 'Look 2nd'), ('Lugam', 'Lugam'), ('Mabolo', 'Mabolo'), ('Mambog', 'Mambog'), ('Masile', 'Masile'), ('Matimbo', 'Matimbo'), ('Mojon', 'Mojon'), ('Namayan', 'Namayan'), ('Niugan', 'Niugan'), ('Pamarawan', 'Pamarawan'), ('Panasahan', 'Panasahan'), ('Pinagbakahan', 'Pinagbakahan'), ('San Agustin', 'San Agustin'), ('San Gabriel', 'San Gabriel'), ('San Juan', 'San Juan'), ('San Pablo', 'San Pablo'), ('Santiago', 'Santiago'), ('Santisima Trinidad', 'Santisima Trinidad'), ('Santo Cristo', 'Santo Cristo'), ('Santor', 'Santor'), ('Santo Niño', 'Santo Niño'), ('Santo Rosario', 'Santo Rosario'), ('San Vicente', 'San Vicente'), ('Sumapang Bata', 'Sumapang Bata'), ('Sumapang Matanda', 'Sumapang Matanda'), ('taal', 'Taal'), ('tikay', 'Tikay')], default='Tikay', max_length=30, verbose_name='Enter your barangay'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='street',
            field=models.CharField(choices=[('Anilao', 'Anilao'), ('Atlag', 'Atlag'), ('Babatnin', 'Babatnin'), ('Bagna', 'Bagna'), ('Bagong Bayan', 'Bagong Bayan'), ('Balayong', 'Balayong'), ('Balite', 'Balite'), ('Bangkal', 'Bangkal'), ('Barihan', 'Barihan'), ('Bulihan', 'Bulihan'), ('Bungahan', 'Bungahan'), ('Caingin', 'Caingin'), ('Calero', 'Calero'), ('Caliligawan', 'Caliligawan'), ('Canalate', 'Canalate'), ('Caniogan', 'Caniogan'), ('Catmon', 'Catmon'), ('Cofradia', 'Cofradia'), ('Dakila', 'Dakila'), ('Guinhawa', 'Guinhawa'), ('Ligas', 'Ligas'), ('Liyang', 'Liyang'), ('longos', 'Longos'), ('Look 1st', 'Look 1st'), ('Look 2nd', 'Look 2nd'), ('Lugam', 'Lugam'), ('Mabolo', 'Mabolo'), ('Mambog', 'Mambog'), ('Masile', 'Masile'), ('Matimbo', 'Matimbo'), ('Mojon', 'Mojon'), ('Namayan', 'Namayan'), ('Niugan', 'Niugan'), ('Pamarawan', 'Pamarawan'), ('Panasahan', 'Panasahan'), ('Pinagbakahan', 'Pinagbakahan'), ('San Agustin', 'San Agustin'), ('San Gabriel', 'San Gabriel'), ('San Juan', 'San Juan'), ('San Pablo', 'San Pablo'), ('Santiago', 'Santiago'), ('Santisima Trinidad', 'Santisima Trinidad'), ('Santo Cristo', 'Santo Cristo'), ('Santor', 'Santor'), ('Santo Niño', 'Santo Niño'), ('Santo Rosario', 'Santo Rosario'), ('San Vicente', 'San Vicente'), ('Sumapang Bata', 'Sumapang Bata'), ('Sumapang Matanda', 'Sumapang Matanda'), ('taal', 'Taal'), ('tikay', 'Tikay')], default='Tikay', max_length=30, verbose_name='Enter your barangay'),
        ),
        migrations.AlterField(
            model_name='post',
            name='street',
            field=models.CharField(choices=[('Anilao', 'Anilao'), ('Atlag', 'Atlag'), ('Babatnin', 'Babatnin'), ('Bagna', 'Bagna'), ('Bagong Bayan', 'Bagong Bayan'), ('Balayong', 'Balayong'), ('Balite', 'Balite'), ('Bangkal', 'Bangkal'), ('Barihan', 'Barihan'), ('Bulihan', 'Bulihan'), ('Bungahan', 'Bungahan'), ('Caingin', 'Caingin'), ('Calero', 'Calero'), ('Caliligawan', 'Caliligawan'), ('Canalate', 'Canalate'), ('Caniogan', 'Caniogan'), ('Catmon', 'Catmon'), ('Cofradia', 'Cofradia'), ('Dakila', 'Dakila'), ('Guinhawa', 'Guinhawa'), ('Ligas', 'Ligas'), ('Liyang', 'Liyang'), ('longos', 'Longos'), ('Look 1st', 'Look 1st'), ('Look 2nd', 'Look 2nd'), ('Lugam', 'Lugam'), ('Mabolo', 'Mabolo'), ('Mambog', 'Mambog'), ('Masile', 'Masile'), ('Matimbo', 'Matimbo'), ('Mojon', 'Mojon'), ('Namayan', 'Namayan'), ('Niugan', 'Niugan'), ('Pamarawan', 'Pamarawan'), ('Panasahan', 'Panasahan'), ('Pinagbakahan', 'Pinagbakahan'), ('San Agustin', 'San Agustin'), ('San Gabriel', 'San Gabriel'), ('San Juan', 'San Juan'), ('San Pablo', 'San Pablo'), ('Santiago', 'Santiago'), ('Santisima Trinidad', 'Santisima Trinidad'), ('Santo Cristo', 'Santo Cristo'), ('Santor', 'Santor'), ('Santo Niño', 'Santo Niño'), ('Santo Rosario', 'Santo Rosario'), ('San Vicente', 'San Vicente'), ('Sumapang Bata', 'Sumapang Bata'), ('Sumapang Matanda', 'Sumapang Matanda'), ('taal', 'Taal'), ('tikay', 'Tikay')], default='Tikay', max_length=30, verbose_name='Enter your barangay'),
        ),
    ]
