# Generated by Django 2.2.7 on 2020-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0039_auto_20200413_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='city',
            field=models.CharField(choices=[('Malolos', 'Malolos')], default='Malolos', max_length=30, verbose_name='Enter your city residence'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='city',
            field=models.CharField(choices=[('Malolos', 'Malolos')], default='Malolos', max_length=30, verbose_name='Enter your city residence'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='city',
            field=models.CharField(choices=[('Malolos', 'Malolos')], default='Malolos', max_length=30, verbose_name='Enter your city residence'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Malolos', 'Malolos')], default='Malolos', max_length=30, verbose_name='Enter your city residence'),
        ),
    ]
