# Generated by Django 2.2.7 on 2020-04-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0041_auto_20200413_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='category',
            field=models.CharField(choices=[('LOGO', 'LOGO'), ('BRAND TAGLINES', 'BRAND TAGLINES'), ('ADVERTISEMENT LAYOUT', 'ADVERTISEMENT LAYOUT'), ('VISUAL ARTS', 'VISUAL ARTS'), ('INTERIOR DESIGN', 'INTERIOR DESIGN')], default='LOGO', max_length=30, verbose_name='Choose your project category'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='category',
            field=models.CharField(choices=[('LOGO', 'LOGO'), ('BRAND TAGLINES', 'BRAND TAGLINES'), ('ADVERTISEMENT LAYOUT', 'ADVERTISEMENT LAYOUT'), ('VISUAL ARTS', 'VISUAL ARTS'), ('INTERIOR DESIGN', 'INTERIOR DESIGN')], default='LOGO', max_length=30, verbose_name='Choose your project category'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('LOGO', 'LOGO'), ('BRAND TAGLINES', 'BRAND TAGLINES'), ('ADVERTISEMENT LAYOUT', 'ADVERTISEMENT LAYOUT'), ('VISUAL ARTS', 'VISUAL ARTS'), ('INTERIOR DESIGN', 'INTERIOR DESIGN')], default='LOGO', max_length=30, verbose_name='Choose your project category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LOGO', 'LOGO'), ('BRAND TAGLINES', 'BRAND TAGLINES'), ('ADVERTISEMENT LAYOUT', 'ADVERTISEMENT LAYOUT'), ('VISUAL ARTS', 'VISUAL ARTS'), ('INTERIOR DESIGN', 'INTERIOR DESIGN')], default='LOGO', max_length=30, verbose_name='Choose your project category'),
        ),
    ]
