# Generated by Django 2.2.7 on 2020-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0043_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verified',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', max_length=100),
        ),
    ]
