# Generated by Django 2.2.7 on 2020-04-29 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home_Business', '0044_post_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='verified',
            field=models.CharField(choices=[('False', 'False')], default='False', max_length=100),
        ),
        migrations.CreateModel(
            name='VerifiedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title (Name your project commission)')),
                ('content', models.TextField(verbose_name='Content (Give a thorough project description)')),
                ('category', models.CharField(choices=[('LOGO', 'LOGO'), ('BRAND TAGLINES', 'BRAND TAGLINES'), ('ADVERTISEMENT LAYOUT', 'ADVERTISEMENT LAYOUT'), ('VISUAL ARTS', 'VISUAL ARTS'), ('INTERIOR DESIGN', 'INTERIOR DESIGN')], default='LOGO', max_length=30, verbose_name='Choose your project category')),
                ('city', models.CharField(choices=[('Malolos', 'Malolos')], default='Malolos', max_length=30, verbose_name='Enter your city residence')),
                ('street', models.CharField(choices=[('Anilao', 'Anilao'), ('Atlag', 'Atlag'), ('Babatnin', 'Babatnin'), ('Bagna', 'Bagna'), ('Bagong Bayan', 'Bagong Bayan'), ('Balayong', 'Balayong'), ('Balite', 'Balite'), ('Bangkal', 'Bangkal'), ('Barihan', 'Barihan'), ('Bulihan', 'Bulihan'), ('Bungahan', 'Bungahan'), ('Caingin', 'Caingin'), ('Calero', 'Calero'), ('Caliligawan', 'Caliligawan'), ('Canalate', 'Canalate'), ('Caniogan', 'Caniogan'), ('Catmon', 'Catmon'), ('Cofradia', 'Cofradia'), ('Dakila', 'Dakila'), ('Guinhawa', 'Guinhawa'), ('Ligas', 'Ligas'), ('Liyang', 'Liyang'), ('longos', 'Longos'), ('Look 1st', 'Look 1st'), ('Look 2nd', 'Look 2nd'), ('Lugam', 'Lugam'), ('Mabolo', 'Mabolo'), ('Mambog', 'Mambog'), ('Masile', 'Masile'), ('Matimbo', 'Matimbo'), ('Mojon', 'Mojon'), ('Namayan', 'Namayan'), ('Niugan', 'Niugan'), ('Pamarawan', 'Pamarawan'), ('Panasahan', 'Panasahan'), ('Pinagbakahan', 'Pinagbakahan'), ('San Agustin', 'San Agustin'), ('San Gabriel', 'San Gabriel'), ('San Juan', 'San Juan'), ('San Pablo', 'San Pablo'), ('Santiago', 'Santiago'), ('Santisima Trinidad', 'Santisima Trinidad'), ('Santo Cristo', 'Santo Cristo'), ('Santor', 'Santor'), ('Santo Niño', 'Santo Niño'), ('Santo Rosario', 'Santo Rosario'), ('San Vicente', 'San Vicente'), ('Sumapang Bata', 'Sumapang Bata'), ('Sumapang Matanda', 'Sumapang Matanda'), ('Taal', 'Taal'), ('Tikay', 'Tikay')], default='Tikay', max_length=30, verbose_name='Enter your barangay')),
                ('dateposted', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.CharField(choices=[('True', 'True')], default='True', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateposted'],
            },
        ),
    ]
