# Generated by Django 2.2.7 on 2020-05-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0045_auto_20200429_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description1',
            field=models.TextField(default='', verbose_name='Project Description (What can you say about this project?)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description2',
            field=models.TextField(default='', verbose_name='Project Description (What can you say about this project?)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description3',
            field=models.TextField(default='', verbose_name='Project Description (What can you say about this project?)'),
        ),
    ]
