# Generated by Django 2.2.7 on 2020-08-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0050_auto_20200803_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='prescreen',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics', verbose_name='Likhanap Pre-screening Results'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='prescreen',
            field=models.ImageField(default='plain.jpg', upload_to='portfolio_pics', verbose_name='Likhanap Pre-screening Results'),
        ),
    ]
