# Generated by Django 2.2.7 on 2020-08-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0051_auto_20200803_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='verified',
            field=models.CharField(choices=[('False', 'False')], default='False', max_length=100),
        ),
    ]
