# Generated by Django 2.2.7 on 2020-08-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0058_auto_20200805_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifiedPost',
        ),
    ]
