# Generated by Django 2.2.7 on 2020-08-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0059_delete_verifiedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='verified',
        ),
    ]
