# Generated by Django 2.2.7 on 2020-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0060_auto_20200805_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='verified',
            field=models.CharField(choices=[('False', 'False')], default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='verified',
            field=models.CharField(choices=[('False', 'False')], default='False', max_length=100),
        ),
    ]
