# Generated by Django 2.2.7 on 2020-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0062_auto_20200805_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.CharField(default='', max_length=100, verbose_name='Settled Rate (How much are you willing to pay for this project?)'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('---', '---')], default='---', max_length=30, verbose_name='Your Project Status'),
        ),
    ]
