# Generated by Django 2.2.7 on 2020-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0065_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='post_pics', verbose_name='Please attach your valid signature'),
        ),
    ]
