# Generated by Django 2.2.7 on 2020-08-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0068_webcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcontract',
            name='artistname',
        ),
        migrations.AddField(
            model_name='webcontract',
            name='businessname',
            field=models.CharField(default='', max_length=100, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='webcontract',
            name='ownername',
            field=models.CharField(default='', max_length=100, verbose_name='Business Owner Name'),
        ),
        migrations.AlterField(
            model_name='webcontract',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Business Owner Address'),
        ),
        migrations.AlterField(
            model_name='webcontract',
            name='category',
            field=models.CharField(choices=[('LOGO', 'LOGO')], default='LOGO', max_length=30, verbose_name='Project Category'),
        ),
    ]
