# Generated by Django 2.2.7 on 2020-08-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0074_agraphiccontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='contract',
            field=models.ImageField(default='plain.jpg', upload_to='contract', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='agraphiccontract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='signatures', verbose_name='Please attach your valid signature'),
        ),
        migrations.AlterField(
            model_name='alogocontract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='signatures', verbose_name='Please attach your valid signature'),
        ),
        migrations.AlterField(
            model_name='awebcontract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='signatures', verbose_name='Please attach your valid signature'),
        ),
        migrations.AlterField(
            model_name='graphiccontract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='signatures', verbose_name='Please attach your valid signature'),
        ),
        migrations.AlterField(
            model_name='logocontract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='signatures', verbose_name='Please attach your valid signature'),
        ),
        migrations.AlterField(
            model_name='webcontract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='signatures', verbose_name='Please attach your valid signature'),
        ),
    ]
