# Generated by Django 2.2.7 on 2020-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0075_auto_20200811_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='contract',
            field=models.ImageField(default='plain.jpg', upload_to='contract', verbose_name='Contract Agreement'),
        ),
    ]
