# Generated by Django 2.2.7 on 2020-08-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0076_auto_20200811_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logocontract',
            name='image',
            field=models.ImageField(default='plain.jpg', upload_to='signatures', verbose_name='Please attach your valid signature (Recommended: .png, 850 x 480 px)'),
        ),
    ]
