# Generated by Django 2.2.7 on 2020-08-11 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home_Business', '0082_auto_20200811_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=100, verbose_name='Business Name')),
                ('ownername', models.CharField(max_length=100, verbose_name='Business Owner Name')),
                ('artistname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('logo', models.ImageField(default='plain.jpg', upload_to='logos', verbose_name='Please attach your valid signature (Recommended: 800 x 800 px)')),
                ('dateposted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
