# Generated by Django 2.2.7 on 2020-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0083_logocertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logocertificate',
            name='logo',
            field=models.ImageField(default='plain.jpg', upload_to='logos', verbose_name='Please your logo image here (Recommended: 800 x 800 px)'),
        ),
    ]
