# Generated by Django 2.2.7 on 2020-08-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0085_webcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcertificate',
            name='link',
            field=models.CharField(max_length=500, verbose_name='Business URL Link'),
        ),
    ]
