# Generated by Django 2.2.7 on 2020-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0088_auto_20200812_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='contract',
            field=models.ImageField(default='contract.png', upload_to='contract', verbose_name='Contract Agreement'),
        ),
    ]
