# Generated by Django 2.2.7 on 2020-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0090_auto_20200812_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logocertificate',
            name='artistname',
            field=models.CharField(max_length=100, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='webcertificate',
            name='artistname',
            field=models.CharField(max_length=100, verbose_name='Artist Name'),
        ),
    ]
