# Generated by Django 2.2.7 on 2020-08-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0092_auto_20200814_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='artist_username',
            field=models.CharField(max_length=100, verbose_name='Please type your commission partner'),
        ),
    ]
