# Generated by Django 2.2.7 on 2020-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0096_auto_20200815_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='f1',
            field=models.TextField(default='', verbose_name='Feedback 1'),
        ),
        migrations.AddField(
            model_name='apply',
            name='f2',
            field=models.TextField(default='', verbose_name='Feedback 2'),
        ),
        migrations.AddField(
            model_name='apply',
            name='f3',
            field=models.TextField(default='', verbose_name='Feedback 3'),
        ),
        migrations.AddField(
            model_name='apply',
            name='overallrating',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Overall Rating'),
        ),
        migrations.AddField(
            model_name='apply',
            name='r1',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Rating 1'),
        ),
        migrations.AddField(
            model_name='apply',
            name='r2',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Rating 2'),
        ),
        migrations.AddField(
            model_name='apply',
            name='r3',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Rating 3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f1',
            field=models.TextField(default='', verbose_name='Feedback 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f2',
            field=models.TextField(default='', verbose_name='Feedback 2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='f3',
            field=models.TextField(default='', verbose_name='Feedback 3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='overallrating',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Overall Rating'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='r1',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Rating 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='r2',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Rating 2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='r3',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Rating 3'),
        ),
    ]
