# Generated by Django 2.2.7 on 2020-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0097_auto_20200817_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='f1',
            field=models.TextField(blank=True, verbose_name='Feedback 1'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='f2',
            field=models.TextField(blank=True, verbose_name='Feedback 2'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='f3',
            field=models.TextField(blank=True, verbose_name='Feedback 3'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='f1',
            field=models.TextField(blank=True, verbose_name='Feedback 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='f2',
            field=models.TextField(blank=True, verbose_name='Feedback 2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='f3',
            field=models.TextField(blank=True, verbose_name='Feedback 3'),
        ),
    ]
