# Generated by Django 2.2.7 on 2020-08-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0099_auto_20200817_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='overallrating',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Overall Rating'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='overallrating',
            field=models.ImageField(default='plain.png', upload_to='', verbose_name='Overall Rating'),
        ),
    ]
