# Generated by Django 2.2.7 on 2020-08-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0100_auto_20200817_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='b1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business 1'),
        ),
        migrations.AddField(
            model_name='apply',
            name='b2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business 2'),
        ),
        migrations.AddField(
            model_name='apply',
            name='b3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business 3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='b1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='b2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business 2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='b3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business 3'),
        ),
    ]
