# Generated by Django 2.2.7 on 2020-08-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0102_auto_20200818_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='b1image',
            field=models.ImageField(default='blank.png', upload_to='', verbose_name='Business 1 image'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='b2image',
            field=models.ImageField(default='blank.png', upload_to='', verbose_name='Business 2 image'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='b3image',
            field=models.ImageField(default='blank.png', upload_to='', verbose_name='Business 3 image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='b1image',
            field=models.ImageField(default='blank.png', upload_to='', verbose_name='Business 1 image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='b2image',
            field=models.ImageField(default='blank.png', upload_to='', verbose_name='Business 2 image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='b3image',
            field=models.ImageField(default='blank.png', upload_to='', verbose_name='Business 3 image'),
        ),
    ]
