# Generated by Django 2.2.7 on 2020-08-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0104_auto_20200818_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='overallrating',
            field=models.ImageField(default='R-0.png', upload_to='overallrating', verbose_name='Overall Rating'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='overallrating',
            field=models.ImageField(default='R-0.png', upload_to='overallrating', verbose_name='Overall Rating'),
        ),
    ]
