# Generated by Django 2.2.7 on 2020-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0106_auto_20200818_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='rate',
            field=models.CharField(default='', max_length=100, verbose_name='Rate of Pay'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rate',
            field=models.CharField(default='', max_length=100, verbose_name='Rate of Pay'),
        ),
    ]
