# Generated by Django 2.2.7 on 2020-08-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0109_auto_20200820_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='Business_username',
            field=models.CharField(default='', max_length=100, verbose_name='Commission partner'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='artist_username',
            field=models.CharField(default='Hans', max_length=100, verbose_name='Commission partner'),
        ),
    ]
