# Generated by Django 2.2.7 on 2020-08-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0110_auto_20200820_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='artist_username',
            field=models.CharField(default='sharlot', max_length=100, verbose_name='Commission Artist:'),
        ),
    ]
