# Generated by Django 2.2.7 on 2020-08-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0112_auto_20200821_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='artist_username',
            field=models.CharField(default='sharlot', max_length=100, verbose_name='Reported Artist:'),
        ),
    ]
