# Generated by Django 2.2.7 on 2020-08-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0114_auto_20200821_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='r1',
            field=models.CharField(choices=[('☆☆☆☆☆', '☆☆☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='☆☆☆☆☆', max_length=30, verbose_name='Choose a Rating:'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='r2',
            field=models.CharField(choices=[('☆☆☆☆☆', '☆☆☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='☆☆☆☆☆', max_length=30, verbose_name='Choose a Rating:'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='r3',
            field=models.CharField(choices=[('☆☆☆☆☆', '☆☆☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='☆☆☆☆☆', max_length=30, verbose_name='Choose a Rating:'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='r1',
            field=models.CharField(choices=[('☆☆☆☆☆', '☆☆☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='☆☆☆☆☆', max_length=30, verbose_name='Choose a Rating:'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='r2',
            field=models.CharField(choices=[('☆☆☆☆☆', '☆☆☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='☆☆☆☆☆', max_length=30, verbose_name='Choose a Rating:'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='r3',
            field=models.CharField(choices=[('☆☆☆☆☆', '☆☆☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='☆☆☆☆☆', max_length=30, verbose_name='Choose a Rating:'),
        ),
    ]
