# Generated by Django 2.2.7 on 2020-08-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Business', '0115_auto_20200821_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='Business_username',
            field=models.CharField(max_length=100, verbose_name='Commission partner'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='artist_username',
            field=models.CharField(max_length=100, verbose_name='Commission partner'),
        ),
    ]
