# Generated by Django 2.2.7 on 2020-04-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200429_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
