# Generated by Django 2.2.7 on 2020-04-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200429_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.CharField(default='False', max_length=30),
        ),
    ]
