# Generated by Django 2.2.7 on 2020-08-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200429_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid',
            field=models.CharField(default='Unpaid', max_length=30),
        ),
    ]
