# Generated by Django 2.2.7 on 2020-08-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid',
            field=models.CharField(default='Free', max_length=30),
        ),
    ]
